/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as StoreRouteImport } from "./routes/store";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as ResetPasswordRouteImport } from "./routes/reset-password";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as FlowgridRouteImport } from "./routes/flowgrid";
import { Route as AppRouteImport } from "./routes/app";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ChronoblogIndexRouteImport } from "./routes/chronoblog/index";
import { Route as ChronoblogSlugRouteImport } from "./routes/chronoblog/$slug";
import { Route as AppWorkflowsRouteImport } from "./routes/app/workflows";
import { Route as AppTimeRouteImport } from "./routes/app/time";
import { Route as AppTasksRouteImport } from "./routes/app/tasks";
import { Route as AppSettingsRouteImport } from "./routes/app/settings";
import { Route as AppMediaRouteImport } from "./routes/app/media";
import { Route as AppMarketplaceRouteImport } from "./routes/app/marketplace";
import { Route as AppJournalRouteImport } from "./routes/app/journal";
import { Route as AppHabitsRouteImport } from "./routes/app/habits";
import { Route as AppGoalsRouteImport } from "./routes/app/goals";
import { Route as AppFinanceRouteImport } from "./routes/app/finance";
import { Route as AppDungeonRouteImport } from "./routes/app/dungeon";
import { Route as AppDashboardRouteImport } from "./routes/app/dashboard";
import { Route as AppCommunitiesRouteImport } from "./routes/app/communities";
import { Route as AppAdminRouteImport } from "./routes/app/admin";
import { Route as AppAdminIndexRouteImport } from "./routes/app/admin.index";
import { Route as AppJournalJournalIdRouteImport } from "./routes/app/journal.$journalId";
import { Route as AppGoalsGoalIdRouteImport } from "./routes/app/goals.$goalId";
import { Route as AppCommunitiesSlugRouteImport } from "./routes/app/communities.$slug";
import { Route as AppAdminWaitlistRouteImport } from "./routes/app/admin.waitlist";
import { Route as AppAdminStoreRouteImport } from "./routes/app/admin.store";
import { Route as AppAdminPreviewRouteImport } from "./routes/app/admin.preview";
import { Route as AppAdminCommunitiesRouteImport } from "./routes/app/admin.communities";
import { Route as AppAdminBlogRouteImport } from "./routes/app/admin.blog";

const StoreRoute = StoreRouteImport.update({
  id: "/store",
  path: "/store",
  getParentRoute: () => rootRouteImport,
} as any);
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const FlowgridRoute = FlowgridRouteImport.update({
  id: "/flowgrid",
  path: "/flowgrid",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ChronoblogIndexRoute = ChronoblogIndexRouteImport.update({
  id: "/chronoblog/",
  path: "/chronoblog/",
  getParentRoute: () => rootRouteImport,
} as any);
const ChronoblogSlugRoute = ChronoblogSlugRouteImport.update({
  id: "/chronoblog/$slug",
  path: "/chronoblog/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => AppRoute,
} as any);
const AppTimeRoute = AppTimeRouteImport.update({
  id: "/time",
  path: "/time",
  getParentRoute: () => AppRoute,
} as any);
const AppTasksRoute = AppTasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => AppRoute,
} as any);
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any);
const AppMediaRoute = AppMediaRouteImport.update({
  id: "/media",
  path: "/media",
  getParentRoute: () => AppRoute,
} as any);
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: "/marketplace",
  path: "/marketplace",
  getParentRoute: () => AppRoute,
} as any);
const AppJournalRoute = AppJournalRouteImport.update({
  id: "/journal",
  path: "/journal",
  getParentRoute: () => AppRoute,
} as any);
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: "/habits",
  path: "/habits",
  getParentRoute: () => AppRoute,
} as any);
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: "/goals",
  path: "/goals",
  getParentRoute: () => AppRoute,
} as any);
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: "/finance",
  path: "/finance",
  getParentRoute: () => AppRoute,
} as any);
const AppDungeonRoute = AppDungeonRouteImport.update({
  id: "/dungeon",
  path: "/dungeon",
  getParentRoute: () => AppRoute,
} as any);
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRoute,
} as any);
const AppCommunitiesRoute = AppCommunitiesRouteImport.update({
  id: "/communities",
  path: "/communities",
  getParentRoute: () => AppRoute,
} as any);
const AppAdminRoute = AppAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AppRoute,
} as any);
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppAdminRoute,
} as any);
const AppJournalJournalIdRoute = AppJournalJournalIdRouteImport.update({
  id: "/$journalId",
  path: "/$journalId",
  getParentRoute: () => AppJournalRoute,
} as any);
const AppGoalsGoalIdRoute = AppGoalsGoalIdRouteImport.update({
  id: "/$goalId",
  path: "/$goalId",
  getParentRoute: () => AppGoalsRoute,
} as any);
const AppCommunitiesSlugRoute = AppCommunitiesSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => AppCommunitiesRoute,
} as any);
const AppAdminWaitlistRoute = AppAdminWaitlistRouteImport.update({
  id: "/waitlist",
  path: "/waitlist",
  getParentRoute: () => AppAdminRoute,
} as any);
const AppAdminStoreRoute = AppAdminStoreRouteImport.update({
  id: "/store",
  path: "/store",
  getParentRoute: () => AppAdminRoute,
} as any);
const AppAdminPreviewRoute = AppAdminPreviewRouteImport.update({
  id: "/preview",
  path: "/preview",
  getParentRoute: () => AppAdminRoute,
} as any);
const AppAdminCommunitiesRoute = AppAdminCommunitiesRouteImport.update({
  id: "/communities",
  path: "/communities",
  getParentRoute: () => AppAdminRoute,
} as any);
const AppAdminBlogRoute = AppAdminBlogRouteImport.update({
  id: "/blog",
  path: "/blog",
  getParentRoute: () => AppAdminRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/app": typeof AppRouteWithChildren;
  "/flowgrid": typeof FlowgridRoute;
  "/login": typeof LoginRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/signup": typeof SignupRoute;
  "/store": typeof StoreRoute;
  "/app/admin": typeof AppAdminRouteWithChildren;
  "/app/communities": typeof AppCommunitiesRouteWithChildren;
  "/app/dashboard": typeof AppDashboardRoute;
  "/app/dungeon": typeof AppDungeonRoute;
  "/app/finance": typeof AppFinanceRoute;
  "/app/goals": typeof AppGoalsRouteWithChildren;
  "/app/habits": typeof AppHabitsRoute;
  "/app/journal": typeof AppJournalRouteWithChildren;
  "/app/marketplace": typeof AppMarketplaceRoute;
  "/app/media": typeof AppMediaRoute;
  "/app/settings": typeof AppSettingsRoute;
  "/app/tasks": typeof AppTasksRoute;
  "/app/time": typeof AppTimeRoute;
  "/app/workflows": typeof AppWorkflowsRoute;
  "/chronoblog/$slug": typeof ChronoblogSlugRoute;
  "/chronoblog/": typeof ChronoblogIndexRoute;
  "/app/admin/blog": typeof AppAdminBlogRoute;
  "/app/admin/communities": typeof AppAdminCommunitiesRoute;
  "/app/admin/preview": typeof AppAdminPreviewRoute;
  "/app/admin/store": typeof AppAdminStoreRoute;
  "/app/admin/waitlist": typeof AppAdminWaitlistRoute;
  "/app/communities/$slug": typeof AppCommunitiesSlugRoute;
  "/app/goals/$goalId": typeof AppGoalsGoalIdRoute;
  "/app/journal/$journalId": typeof AppJournalJournalIdRoute;
  "/app/admin/": typeof AppAdminIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/app": typeof AppRouteWithChildren;
  "/flowgrid": typeof FlowgridRoute;
  "/login": typeof LoginRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/signup": typeof SignupRoute;
  "/store": typeof StoreRoute;
  "/app/communities": typeof AppCommunitiesRouteWithChildren;
  "/app/dashboard": typeof AppDashboardRoute;
  "/app/dungeon": typeof AppDungeonRoute;
  "/app/finance": typeof AppFinanceRoute;
  "/app/goals": typeof AppGoalsRouteWithChildren;
  "/app/habits": typeof AppHabitsRoute;
  "/app/journal": typeof AppJournalRouteWithChildren;
  "/app/marketplace": typeof AppMarketplaceRoute;
  "/app/media": typeof AppMediaRoute;
  "/app/settings": typeof AppSettingsRoute;
  "/app/tasks": typeof AppTasksRoute;
  "/app/time": typeof AppTimeRoute;
  "/app/workflows": typeof AppWorkflowsRoute;
  "/chronoblog/$slug": typeof ChronoblogSlugRoute;
  "/chronoblog": typeof ChronoblogIndexRoute;
  "/app/admin/blog": typeof AppAdminBlogRoute;
  "/app/admin/communities": typeof AppAdminCommunitiesRoute;
  "/app/admin/preview": typeof AppAdminPreviewRoute;
  "/app/admin/store": typeof AppAdminStoreRoute;
  "/app/admin/waitlist": typeof AppAdminWaitlistRoute;
  "/app/communities/$slug": typeof AppCommunitiesSlugRoute;
  "/app/goals/$goalId": typeof AppGoalsGoalIdRoute;
  "/app/journal/$journalId": typeof AppJournalJournalIdRoute;
  "/app/admin": typeof AppAdminIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/app": typeof AppRouteWithChildren;
  "/flowgrid": typeof FlowgridRoute;
  "/login": typeof LoginRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/signup": typeof SignupRoute;
  "/store": typeof StoreRoute;
  "/app/admin": typeof AppAdminRouteWithChildren;
  "/app/communities": typeof AppCommunitiesRouteWithChildren;
  "/app/dashboard": typeof AppDashboardRoute;
  "/app/dungeon": typeof AppDungeonRoute;
  "/app/finance": typeof AppFinanceRoute;
  "/app/goals": typeof AppGoalsRouteWithChildren;
  "/app/habits": typeof AppHabitsRoute;
  "/app/journal": typeof AppJournalRouteWithChildren;
  "/app/marketplace": typeof AppMarketplaceRoute;
  "/app/media": typeof AppMediaRoute;
  "/app/settings": typeof AppSettingsRoute;
  "/app/tasks": typeof AppTasksRoute;
  "/app/time": typeof AppTimeRoute;
  "/app/workflows": typeof AppWorkflowsRoute;
  "/chronoblog/$slug": typeof ChronoblogSlugRoute;
  "/chronoblog/": typeof ChronoblogIndexRoute;
  "/app/admin/blog": typeof AppAdminBlogRoute;
  "/app/admin/communities": typeof AppAdminCommunitiesRoute;
  "/app/admin/preview": typeof AppAdminPreviewRoute;
  "/app/admin/store": typeof AppAdminStoreRoute;
  "/app/admin/waitlist": typeof AppAdminWaitlistRoute;
  "/app/communities/$slug": typeof AppCommunitiesSlugRoute;
  "/app/goals/$goalId": typeof AppGoalsGoalIdRoute;
  "/app/journal/$journalId": typeof AppJournalJournalIdRoute;
  "/app/admin/": typeof AppAdminIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/app"
    | "/flowgrid"
    | "/login"
    | "/reset-password"
    | "/signup"
    | "/store"
    | "/app/admin"
    | "/app/communities"
    | "/app/dashboard"
    | "/app/dungeon"
    | "/app/finance"
    | "/app/goals"
    | "/app/habits"
    | "/app/journal"
    | "/app/marketplace"
    | "/app/media"
    | "/app/settings"
    | "/app/tasks"
    | "/app/time"
    | "/app/workflows"
    | "/chronoblog/$slug"
    | "/chronoblog/"
    | "/app/admin/blog"
    | "/app/admin/communities"
    | "/app/admin/preview"
    | "/app/admin/store"
    | "/app/admin/waitlist"
    | "/app/communities/$slug"
    | "/app/goals/$goalId"
    | "/app/journal/$journalId"
    | "/app/admin/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/app"
    | "/flowgrid"
    | "/login"
    | "/reset-password"
    | "/signup"
    | "/store"
    | "/app/communities"
    | "/app/dashboard"
    | "/app/dungeon"
    | "/app/finance"
    | "/app/goals"
    | "/app/habits"
    | "/app/journal"
    | "/app/marketplace"
    | "/app/media"
    | "/app/settings"
    | "/app/tasks"
    | "/app/time"
    | "/app/workflows"
    | "/chronoblog/$slug"
    | "/chronoblog"
    | "/app/admin/blog"
    | "/app/admin/communities"
    | "/app/admin/preview"
    | "/app/admin/store"
    | "/app/admin/waitlist"
    | "/app/communities/$slug"
    | "/app/goals/$goalId"
    | "/app/journal/$journalId"
    | "/app/admin";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/app"
    | "/flowgrid"
    | "/login"
    | "/reset-password"
    | "/signup"
    | "/store"
    | "/app/admin"
    | "/app/communities"
    | "/app/dashboard"
    | "/app/dungeon"
    | "/app/finance"
    | "/app/goals"
    | "/app/habits"
    | "/app/journal"
    | "/app/marketplace"
    | "/app/media"
    | "/app/settings"
    | "/app/tasks"
    | "/app/time"
    | "/app/workflows"
    | "/chronoblog/$slug"
    | "/chronoblog/"
    | "/app/admin/blog"
    | "/app/admin/communities"
    | "/app/admin/preview"
    | "/app/admin/store"
    | "/app/admin/waitlist"
    | "/app/communities/$slug"
    | "/app/goals/$goalId"
    | "/app/journal/$journalId"
    | "/app/admin/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  AppRoute: typeof AppRouteWithChildren;
  FlowgridRoute: typeof FlowgridRoute;
  LoginRoute: typeof LoginRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  SignupRoute: typeof SignupRoute;
  StoreRoute: typeof StoreRoute;
  ChronoblogSlugRoute: typeof ChronoblogSlugRoute;
  ChronoblogIndexRoute: typeof ChronoblogIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/store": {
      id: "/store";
      path: "/store";
      fullPath: "/store";
      preLoaderRoute: typeof StoreRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reset-password": {
      id: "/reset-password";
      path: "/reset-password";
      fullPath: "/reset-password";
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/flowgrid": {
      id: "/flowgrid";
      path: "/flowgrid";
      fullPath: "/flowgrid";
      preLoaderRoute: typeof FlowgridRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app": {
      id: "/app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chronoblog/": {
      id: "/chronoblog/";
      path: "/chronoblog";
      fullPath: "/chronoblog/";
      preLoaderRoute: typeof ChronoblogIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chronoblog/$slug": {
      id: "/chronoblog/$slug";
      path: "/chronoblog/$slug";
      fullPath: "/chronoblog/$slug";
      preLoaderRoute: typeof ChronoblogSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/workflows": {
      id: "/app/workflows";
      path: "/workflows";
      fullPath: "/app/workflows";
      preLoaderRoute: typeof AppWorkflowsRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/time": {
      id: "/app/time";
      path: "/time";
      fullPath: "/app/time";
      preLoaderRoute: typeof AppTimeRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/tasks": {
      id: "/app/tasks";
      path: "/tasks";
      fullPath: "/app/tasks";
      preLoaderRoute: typeof AppTasksRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/settings": {
      id: "/app/settings";
      path: "/settings";
      fullPath: "/app/settings";
      preLoaderRoute: typeof AppSettingsRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/media": {
      id: "/app/media";
      path: "/media";
      fullPath: "/app/media";
      preLoaderRoute: typeof AppMediaRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/marketplace": {
      id: "/app/marketplace";
      path: "/marketplace";
      fullPath: "/app/marketplace";
      preLoaderRoute: typeof AppMarketplaceRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/journal": {
      id: "/app/journal";
      path: "/journal";
      fullPath: "/app/journal";
      preLoaderRoute: typeof AppJournalRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/habits": {
      id: "/app/habits";
      path: "/habits";
      fullPath: "/app/habits";
      preLoaderRoute: typeof AppHabitsRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/goals": {
      id: "/app/goals";
      path: "/goals";
      fullPath: "/app/goals";
      preLoaderRoute: typeof AppGoalsRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/finance": {
      id: "/app/finance";
      path: "/finance";
      fullPath: "/app/finance";
      preLoaderRoute: typeof AppFinanceRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/dungeon": {
      id: "/app/dungeon";
      path: "/dungeon";
      fullPath: "/app/dungeon";
      preLoaderRoute: typeof AppDungeonRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/dashboard": {
      id: "/app/dashboard";
      path: "/dashboard";
      fullPath: "/app/dashboard";
      preLoaderRoute: typeof AppDashboardRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/communities": {
      id: "/app/communities";
      path: "/communities";
      fullPath: "/app/communities";
      preLoaderRoute: typeof AppCommunitiesRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/admin": {
      id: "/app/admin";
      path: "/admin";
      fullPath: "/app/admin";
      preLoaderRoute: typeof AppAdminRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/admin/": {
      id: "/app/admin/";
      path: "/";
      fullPath: "/app/admin/";
      preLoaderRoute: typeof AppAdminIndexRouteImport;
      parentRoute: typeof AppAdminRoute;
    };
    "/app/journal/$journalId": {
      id: "/app/journal/$journalId";
      path: "/$journalId";
      fullPath: "/app/journal/$journalId";
      preLoaderRoute: typeof AppJournalJournalIdRouteImport;
      parentRoute: typeof AppJournalRoute;
    };
    "/app/goals/$goalId": {
      id: "/app/goals/$goalId";
      path: "/$goalId";
      fullPath: "/app/goals/$goalId";
      preLoaderRoute: typeof AppGoalsGoalIdRouteImport;
      parentRoute: typeof AppGoalsRoute;
    };
    "/app/communities/$slug": {
      id: "/app/communities/$slug";
      path: "/$slug";
      fullPath: "/app/communities/$slug";
      preLoaderRoute: typeof AppCommunitiesSlugRouteImport;
      parentRoute: typeof AppCommunitiesRoute;
    };
    "/app/admin/waitlist": {
      id: "/app/admin/waitlist";
      path: "/waitlist";
      fullPath: "/app/admin/waitlist";
      preLoaderRoute: typeof AppAdminWaitlistRouteImport;
      parentRoute: typeof AppAdminRoute;
    };
    "/app/admin/store": {
      id: "/app/admin/store";
      path: "/store";
      fullPath: "/app/admin/store";
      preLoaderRoute: typeof AppAdminStoreRouteImport;
      parentRoute: typeof AppAdminRoute;
    };
    "/app/admin/preview": {
      id: "/app/admin/preview";
      path: "/preview";
      fullPath: "/app/admin/preview";
      preLoaderRoute: typeof AppAdminPreviewRouteImport;
      parentRoute: typeof AppAdminRoute;
    };
    "/app/admin/communities": {
      id: "/app/admin/communities";
      path: "/communities";
      fullPath: "/app/admin/communities";
      preLoaderRoute: typeof AppAdminCommunitiesRouteImport;
      parentRoute: typeof AppAdminRoute;
    };
    "/app/admin/blog": {
      id: "/app/admin/blog";
      path: "/blog";
      fullPath: "/app/admin/blog";
      preLoaderRoute: typeof AppAdminBlogRouteImport;
      parentRoute: typeof AppAdminRoute;
    };
  }
}

interface AppAdminRouteChildren {
  AppAdminBlogRoute: typeof AppAdminBlogRoute;
  AppAdminCommunitiesRoute: typeof AppAdminCommunitiesRoute;
  AppAdminPreviewRoute: typeof AppAdminPreviewRoute;
  AppAdminStoreRoute: typeof AppAdminStoreRoute;
  AppAdminWaitlistRoute: typeof AppAdminWaitlistRoute;
  AppAdminIndexRoute: typeof AppAdminIndexRoute;
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBlogRoute: AppAdminBlogRoute,
  AppAdminCommunitiesRoute: AppAdminCommunitiesRoute,
  AppAdminPreviewRoute: AppAdminPreviewRoute,
  AppAdminStoreRoute: AppAdminStoreRoute,
  AppAdminWaitlistRoute: AppAdminWaitlistRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
};

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
);

interface AppCommunitiesRouteChildren {
  AppCommunitiesSlugRoute: typeof AppCommunitiesSlugRoute;
}

const AppCommunitiesRouteChildren: AppCommunitiesRouteChildren = {
  AppCommunitiesSlugRoute: AppCommunitiesSlugRoute,
};

const AppCommunitiesRouteWithChildren = AppCommunitiesRoute._addFileChildren(
  AppCommunitiesRouteChildren,
);

interface AppGoalsRouteChildren {
  AppGoalsGoalIdRoute: typeof AppGoalsGoalIdRoute;
}

const AppGoalsRouteChildren: AppGoalsRouteChildren = {
  AppGoalsGoalIdRoute: AppGoalsGoalIdRoute,
};

const AppGoalsRouteWithChildren = AppGoalsRoute._addFileChildren(
  AppGoalsRouteChildren,
);

interface AppJournalRouteChildren {
  AppJournalJournalIdRoute: typeof AppJournalJournalIdRoute;
}

const AppJournalRouteChildren: AppJournalRouteChildren = {
  AppJournalJournalIdRoute: AppJournalJournalIdRoute,
};

const AppJournalRouteWithChildren = AppJournalRoute._addFileChildren(
  AppJournalRouteChildren,
);

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren;
  AppCommunitiesRoute: typeof AppCommunitiesRouteWithChildren;
  AppDashboardRoute: typeof AppDashboardRoute;
  AppDungeonRoute: typeof AppDungeonRoute;
  AppFinanceRoute: typeof AppFinanceRoute;
  AppGoalsRoute: typeof AppGoalsRouteWithChildren;
  AppHabitsRoute: typeof AppHabitsRoute;
  AppJournalRoute: typeof AppJournalRouteWithChildren;
  AppMarketplaceRoute: typeof AppMarketplaceRoute;
  AppMediaRoute: typeof AppMediaRoute;
  AppSettingsRoute: typeof AppSettingsRoute;
  AppTasksRoute: typeof AppTasksRoute;
  AppTimeRoute: typeof AppTimeRoute;
  AppWorkflowsRoute: typeof AppWorkflowsRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCommunitiesRoute: AppCommunitiesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDungeonRoute: AppDungeonRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppGoalsRoute: AppGoalsRouteWithChildren,
  AppHabitsRoute: AppHabitsRoute,
  AppJournalRoute: AppJournalRouteWithChildren,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMediaRoute: AppMediaRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTimeRoute: AppTimeRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  FlowgridRoute: FlowgridRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StoreRoute: StoreRoute,
  ChronoblogSlugRoute: ChronoblogSlugRoute,
  ChronoblogIndexRoute: ChronoblogIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
