/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as AppRouteImport } from "./routes/app";
import { Route as FlowgridRouteImport } from "./routes/flowgrid";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ResetPasswordRouteImport } from "./routes/reset-password";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as StoreRouteImport } from "./routes/store";
import { Route as AppAdminRouteImport } from "./routes/app/admin";
import { Route as AppCommunicationRouteImport } from "./routes/app/communication";
import { Route as AppDashboardRouteImport } from "./routes/app/dashboard";
import { Route as AppFilesRouteImport } from "./routes/app/files";
import { Route as AppFinanceRouteImport } from "./routes/app/finance";
import { Route as AppOnboardingRouteImport } from "./routes/app/onboarding";
import { Route as AppProjectRouteImport } from "./routes/app/project";
import { Route as AppSettingsRouteImport } from "./routes/app/settings";
import { Route as ChronoblogIndexRouteImport } from "./routes/chronoblog/index";
import { Route as ChronoblogSlugRouteImport } from "./routes/chronoblog/$slug";
import { Route as JoinTokenRouteImport } from "./routes/join/$token";
import { Route as AppAdminIndexRouteImport } from "./routes/app/admin.index";
import { Route as AppAdminBlogRouteImport } from "./routes/app/admin.blog";
import { Route as AppAdminPreviewRouteImport } from "./routes/app/admin.preview";
import { Route as AppAdminStoreRouteImport } from "./routes/app/admin.store";
import { Route as AppAdminWaitlistRouteImport } from "./routes/app/admin.waitlist";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any);
const FlowgridRoute = FlowgridRouteImport.update({
  id: "/flowgrid",
  path: "/flowgrid",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any);
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const StoreRoute = StoreRouteImport.update({
  id: "/store",
  path: "/store",
  getParentRoute: () => rootRouteImport,
} as any);
const AppAdminRoute = AppAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AppRoute,
} as any);
const AppCommunicationRoute = AppCommunicationRouteImport.update({
  id: "/communication",
  path: "/communication",
  getParentRoute: () => AppRoute,
} as any);
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRoute,
} as any);
const AppFilesRoute = AppFilesRouteImport.update({
  id: "/files",
  path: "/files",
  getParentRoute: () => AppRoute,
} as any);
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: "/finance",
  path: "/finance",
  getParentRoute: () => AppRoute,
} as any);
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => AppRoute,
} as any);
const AppProjectRoute = AppProjectRouteImport.update({
  id: "/project",
  path: "/project",
  getParentRoute: () => AppRoute,
} as any);
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any);
const ChronoblogIndexRoute = ChronoblogIndexRouteImport.update({
  id: "/chronoblog/",
  path: "/chronoblog/",
  getParentRoute: () => rootRouteImport,
} as any);
const ChronoblogSlugRoute = ChronoblogSlugRouteImport.update({
  id: "/chronoblog/$slug",
  path: "/chronoblog/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: "/join/$token",
  path: "/join/$token",
  getParentRoute: () => rootRouteImport,
} as any);
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppAdminRoute,
} as any);
const AppAdminBlogRoute = AppAdminBlogRouteImport.update({
  id: "/blog",
  path: "/blog",
  getParentRoute: () => AppAdminRoute,
} as any);
const AppAdminPreviewRoute = AppAdminPreviewRouteImport.update({
  id: "/preview",
  path: "/preview",
  getParentRoute: () => AppAdminRoute,
} as any);
const AppAdminStoreRoute = AppAdminStoreRouteImport.update({
  id: "/store",
  path: "/store",
  getParentRoute: () => AppAdminRoute,
} as any);
const AppAdminWaitlistRoute = AppAdminWaitlistRouteImport.update({
  id: "/waitlist",
  path: "/waitlist",
  getParentRoute: () => AppAdminRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/app": typeof AppRouteWithChildren;
  "/flowgrid": typeof FlowgridRoute;
  "/login": typeof LoginRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/signup": typeof SignupRoute;
  "/store": typeof StoreRoute;
  "/app/admin": typeof AppAdminRouteWithChildren;
  "/app/communication": typeof AppCommunicationRoute;
  "/app/dashboard": typeof AppDashboardRoute;
  "/app/files": typeof AppFilesRoute;
  "/app/finance": typeof AppFinanceRoute;
  "/app/onboarding": typeof AppOnboardingRoute;
  "/app/project": typeof AppProjectRoute;
  "/app/settings": typeof AppSettingsRoute;
  "/chronoblog/$slug": typeof ChronoblogSlugRoute;
  "/join/$token": typeof JoinTokenRoute;
  "/chronoblog/": typeof ChronoblogIndexRoute;
  "/app/admin/blog": typeof AppAdminBlogRoute;
  "/app/admin/preview": typeof AppAdminPreviewRoute;
  "/app/admin/store": typeof AppAdminStoreRoute;
  "/app/admin/waitlist": typeof AppAdminWaitlistRoute;
  "/app/admin/": typeof AppAdminIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/app": typeof AppRouteWithChildren;
  "/flowgrid": typeof FlowgridRoute;
  "/login": typeof LoginRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/signup": typeof SignupRoute;
  "/store": typeof StoreRoute;
  "/app/communication": typeof AppCommunicationRoute;
  "/app/dashboard": typeof AppDashboardRoute;
  "/app/files": typeof AppFilesRoute;
  "/app/finance": typeof AppFinanceRoute;
  "/app/onboarding": typeof AppOnboardingRoute;
  "/app/project": typeof AppProjectRoute;
  "/app/settings": typeof AppSettingsRoute;
  "/chronoblog/$slug": typeof ChronoblogSlugRoute;
  "/join/$token": typeof JoinTokenRoute;
  "/chronoblog": typeof ChronoblogIndexRoute;
  "/app/admin/blog": typeof AppAdminBlogRoute;
  "/app/admin/preview": typeof AppAdminPreviewRoute;
  "/app/admin/store": typeof AppAdminStoreRoute;
  "/app/admin/waitlist": typeof AppAdminWaitlistRoute;
  "/app/admin": typeof AppAdminIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/app": typeof AppRouteWithChildren;
  "/flowgrid": typeof FlowgridRoute;
  "/login": typeof LoginRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/signup": typeof SignupRoute;
  "/store": typeof StoreRoute;
  "/app/admin": typeof AppAdminRouteWithChildren;
  "/app/communication": typeof AppCommunicationRoute;
  "/app/dashboard": typeof AppDashboardRoute;
  "/app/files": typeof AppFilesRoute;
  "/app/finance": typeof AppFinanceRoute;
  "/app/onboarding": typeof AppOnboardingRoute;
  "/app/project": typeof AppProjectRoute;
  "/app/settings": typeof AppSettingsRoute;
  "/chronoblog/$slug": typeof ChronoblogSlugRoute;
  "/join/$token": typeof JoinTokenRoute;
  "/chronoblog/": typeof ChronoblogIndexRoute;
  "/app/admin/blog": typeof AppAdminBlogRoute;
  "/app/admin/preview": typeof AppAdminPreviewRoute;
  "/app/admin/store": typeof AppAdminStoreRoute;
  "/app/admin/waitlist": typeof AppAdminWaitlistRoute;
  "/app/admin/": typeof AppAdminIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/app"
    | "/flowgrid"
    | "/login"
    | "/reset-password"
    | "/signup"
    | "/store"
    | "/app/admin"
    | "/app/communication"
    | "/app/dashboard"
    | "/app/files"
    | "/app/finance"
    | "/app/onboarding"
    | "/app/project"
    | "/app/settings"
    | "/chronoblog/$slug"
    | "/join/$token"
    | "/chronoblog/"
    | "/app/admin/blog"
    | "/app/admin/preview"
    | "/app/admin/store"
    | "/app/admin/waitlist"
    | "/app/admin/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/app"
    | "/flowgrid"
    | "/login"
    | "/reset-password"
    | "/signup"
    | "/store"
    | "/app/communication"
    | "/app/dashboard"
    | "/app/files"
    | "/app/finance"
    | "/app/onboarding"
    | "/app/project"
    | "/app/settings"
    | "/chronoblog/$slug"
    | "/join/$token"
    | "/chronoblog"
    | "/app/admin/blog"
    | "/app/admin/preview"
    | "/app/admin/store"
    | "/app/admin/waitlist"
    | "/app/admin";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/app"
    | "/flowgrid"
    | "/login"
    | "/reset-password"
    | "/signup"
    | "/store"
    | "/app/admin"
    | "/app/communication"
    | "/app/dashboard"
    | "/app/files"
    | "/app/finance"
    | "/app/onboarding"
    | "/app/project"
    | "/app/settings"
    | "/chronoblog/$slug"
    | "/join/$token"
    | "/chronoblog/"
    | "/app/admin/blog"
    | "/app/admin/preview"
    | "/app/admin/store"
    | "/app/admin/waitlist"
    | "/app/admin/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  AppRoute: typeof AppRouteWithChildren;
  FlowgridRoute: typeof FlowgridRoute;
  LoginRoute: typeof LoginRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  SignupRoute: typeof SignupRoute;
  StoreRoute: typeof StoreRoute;
  ChronoblogSlugRoute: typeof ChronoblogSlugRoute;
  JoinTokenRoute: typeof JoinTokenRoute;
  ChronoblogIndexRoute: typeof ChronoblogIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app": {
      id: "/app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/flowgrid": {
      id: "/flowgrid";
      path: "/flowgrid";
      fullPath: "/flowgrid";
      preLoaderRoute: typeof FlowgridRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reset-password": {
      id: "/reset-password";
      path: "/reset-password";
      fullPath: "/reset-password";
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/store": {
      id: "/store";
      path: "/store";
      fullPath: "/store";
      preLoaderRoute: typeof StoreRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/admin": {
      id: "/app/admin";
      path: "/admin";
      fullPath: "/app/admin";
      preLoaderRoute: typeof AppAdminRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/communication": {
      id: "/app/communication";
      path: "/communication";
      fullPath: "/app/communication";
      preLoaderRoute: typeof AppCommunicationRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/dashboard": {
      id: "/app/dashboard";
      path: "/dashboard";
      fullPath: "/app/dashboard";
      preLoaderRoute: typeof AppDashboardRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/files": {
      id: "/app/files";
      path: "/files";
      fullPath: "/app/files";
      preLoaderRoute: typeof AppFilesRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/finance": {
      id: "/app/finance";
      path: "/finance";
      fullPath: "/app/finance";
      preLoaderRoute: typeof AppFinanceRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/onboarding": {
      id: "/app/onboarding";
      path: "/onboarding";
      fullPath: "/app/onboarding";
      preLoaderRoute: typeof AppOnboardingRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/project": {
      id: "/app/project";
      path: "/project";
      fullPath: "/app/project";
      preLoaderRoute: typeof AppProjectRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/settings": {
      id: "/app/settings";
      path: "/settings";
      fullPath: "/app/settings";
      preLoaderRoute: typeof AppSettingsRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/chronoblog/": {
      id: "/chronoblog/";
      path: "/chronoblog";
      fullPath: "/chronoblog/";
      preLoaderRoute: typeof ChronoblogIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chronoblog/$slug": {
      id: "/chronoblog/$slug";
      path: "/chronoblog/$slug";
      fullPath: "/chronoblog/$slug";
      preLoaderRoute: typeof ChronoblogSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/join/$token": {
      id: "/join/$token";
      path: "/join/$token";
      fullPath: "/join/$token";
      preLoaderRoute: typeof JoinTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/admin/": {
      id: "/app/admin/";
      path: "/";
      fullPath: "/app/admin/";
      preLoaderRoute: typeof AppAdminIndexRouteImport;
      parentRoute: typeof AppAdminRoute;
    };
    "/app/admin/blog": {
      id: "/app/admin/blog";
      path: "/blog";
      fullPath: "/app/admin/blog";
      preLoaderRoute: typeof AppAdminBlogRouteImport;
      parentRoute: typeof AppAdminRoute;
    };
    "/app/admin/preview": {
      id: "/app/admin/preview";
      path: "/preview";
      fullPath: "/app/admin/preview";
      preLoaderRoute: typeof AppAdminPreviewRouteImport;
      parentRoute: typeof AppAdminRoute;
    };
    "/app/admin/store": {
      id: "/app/admin/store";
      path: "/store";
      fullPath: "/app/admin/store";
      preLoaderRoute: typeof AppAdminStoreRouteImport;
      parentRoute: typeof AppAdminRoute;
    };
    "/app/admin/waitlist": {
      id: "/app/admin/waitlist";
      path: "/waitlist";
      fullPath: "/app/admin/waitlist";
      preLoaderRoute: typeof AppAdminWaitlistRouteImport;
      parentRoute: typeof AppAdminRoute;
    };
  }
}

interface AppAdminRouteChildren {
  AppAdminBlogRoute: typeof AppAdminBlogRoute;
  AppAdminPreviewRoute: typeof AppAdminPreviewRoute;
  AppAdminStoreRoute: typeof AppAdminStoreRoute;
  AppAdminWaitlistRoute: typeof AppAdminWaitlistRoute;
  AppAdminIndexRoute: typeof AppAdminIndexRoute;
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBlogRoute: AppAdminBlogRoute,
  AppAdminPreviewRoute: AppAdminPreviewRoute,
  AppAdminStoreRoute: AppAdminStoreRoute,
  AppAdminWaitlistRoute: AppAdminWaitlistRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
};

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
);

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren;
  AppCommunicationRoute: typeof AppCommunicationRoute;
  AppDashboardRoute: typeof AppDashboardRoute;
  AppFilesRoute: typeof AppFilesRoute;
  AppFinanceRoute: typeof AppFinanceRoute;
  AppOnboardingRoute: typeof AppOnboardingRoute;
  AppProjectRoute: typeof AppProjectRoute;
  AppSettingsRoute: typeof AppSettingsRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCommunicationRoute: AppCommunicationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFilesRoute: AppFilesRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProjectRoute: AppProjectRoute,
  AppSettingsRoute: AppSettingsRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  FlowgridRoute: FlowgridRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StoreRoute: StoreRoute,
  ChronoblogSlugRoute: ChronoblogSlugRoute,
  JoinTokenRoute: JoinTokenRoute,
  ChronoblogIndexRoute: ChronoblogIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
